/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Controller.PalomaController;
import Domain.Paloma;
import Utils.Utils;
import java.time.LocalDate;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Carlos
 */
public class AltaPalomaPanel extends javax.swing.JPanel {

    /**
     * Creates new form nuevaPanel
     */
    public AltaPalomaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tipoButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacionesTextArea = new javax.swing.JTextArea();
        anillaTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        nacimientoDateChooser = new com.toedter.calendar.JDateChooser();
        machoRadioButton = new javax.swing.JRadioButton();
        hembraRadioButton = new javax.swing.JRadioButton();
        colorTextField = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        vueloRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        crianzaRadioButton = new javax.swing.JRadioButton();

        jLabel1.setText("ANILLA:");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("FECHA:");

        jLabel4.setText("COLOR:");

        jLabel5.setText("SEXO:");

        jLabel6.setText("OBSERVACIONES");

        observacionesTextArea.setColumns(20);
        observacionesTextArea.setRows(5);
        jScrollPane1.setViewportView(observacionesTextArea);

        buttonGroup1.add(machoRadioButton);
        machoRadioButton.setText("MACHO");

        buttonGroup1.add(hembraRadioButton);
        hembraRadioButton.setText("HEMBRA");

        guardarButton.setText("GUARDAR");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        tipoButtonGroup.add(vueloRadioButton);
        vueloRadioButton.setText("VUELO");

        jLabel7.setText("TIPO:");

        tipoButtonGroup.add(crianzaRadioButton);
        crianzaRadioButton.setText("CRIANZA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anillaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(machoRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(hembraRadioButton)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nacimientoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(vueloRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(crianzaRadioButton)))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(guardarButton)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(anillaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacimientoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(machoRadioButton)
                    .addComponent(hembraRadioButton)
                    .addComponent(jLabel5)
                    .addComponent(vueloRadioButton)
                    .addComponent(jLabel7)
                    .addComponent(crianzaRadioButton))
                .addGap(63, 63, 63)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardarButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
       
        if(!Utils.checkField(anillaTextField, 30)){
            JOptionPane.showMessageDialog(this, "El campo anilla no puede estar vacío ni tener más de 30 caracteres.");
            return;
        }
        
        String anilla = anillaTextField.getText();
        String nombre = nombreTextField.getText();
        LocalDate nacimiento = Utils.checkDateChooser(nacimientoDateChooser);
        if(nacimiento == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de nacimiento.");
            return;
        }
        String color = colorTextField.getText(); 
        boolean tipo = vueloRadioButton.isSelected() ? true : false;
        
        String sexoStr = "";
        if(buttonGroup1.getSelection() == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un sexo.");
            return;
        }
        if(machoRadioButton.isSelected()){
            sexoStr = "M";
        } 
        else if(hembraRadioButton.isSelected()){
            sexoStr = "H";
        }
        char sexo = sexoStr.charAt(0); 
        String observaciones = observacionesTextArea.getText();

        Paloma nuevaPaloma = new Paloma(anilla, nombre, nacimiento, sexo, color, tipo, observaciones);
        
        if(PalomaController.nuevaPaloma(nuevaPaloma)){
            JOptionPane.showMessageDialog(this,"Paloma con nº de anilla " + anilla + " guardada correctamente.");
            JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
            dialog.dispose();
        }
    }//GEN-LAST:event_guardarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anillaTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JRadioButton crianzaRadioButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JRadioButton hembraRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton machoRadioButton;
    private com.toedter.calendar.JDateChooser nacimientoDateChooser;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextArea observacionesTextArea;
    private javax.swing.ButtonGroup tipoButtonGroup;
    private javax.swing.JRadioButton vueloRadioButton;
    // End of variables declaration//GEN-END:variables
}
