/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Controller.PalomaController;
import Controller.ParejaController;
import Domain.Paloma;
import Utils.Utils;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author sovi8
 */
public class PalomaDetallePanel extends javax.swing.JPanel {

    /**
     * Creates new form PalomaDetallerPanel
     */
    private Paloma paloma = new Paloma();
    
    public PalomaDetallePanel(Paloma paloma) {
        initComponents();
        this.paloma = paloma;
        cargarDatosPaloma(paloma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacionesTextArea = new javax.swing.JTextArea();
        modificarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        arbolButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        anillaTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        machoRadioButton = new javax.swing.JRadioButton();
        hembraRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        parejaActualTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vueloRadioButton = new javax.swing.JRadioButton();
        crianzaRadioButton = new javax.swing.JRadioButton();
        nacimientoDateChooser = new com.toedter.calendar.JDateChooser();
        parejasButton = new javax.swing.JButton();
        emparejarButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setPreferredSize(new java.awt.Dimension(610, 500));

        jLabel1.setText("ANILLA:");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("FECHA:");

        jLabel4.setText("SEXO:");

        jLabel5.setText("COLOR:");

        jLabel6.setText("OBSERVACIONES");

        observacionesTextArea.setColumns(20);
        observacionesTextArea.setRows(5);
        jScrollPane1.setViewportView(observacionesTextArea);

        modificarButton.setText("GUARDAR MODIFICACION");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("ELIMINAR");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        arbolButton.setText("ARBOL");

        salirButton.setText("SALIR");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(machoRadioButton);
        machoRadioButton.setText("MACHO");

        buttonGroup1.add(hembraRadioButton);
        hembraRadioButton.setText("HEMBRA");

        jLabel7.setText("PAREJA ACTUAL:");

        jLabel8.setText("TIPO:");

        buttonGroup2.add(vueloRadioButton);
        vueloRadioButton.setText("VUELO");

        buttonGroup2.add(crianzaRadioButton);
        crianzaRadioButton.setText("CRIANZA");

        parejasButton.setText("LISTAR PAREJAS");
        parejasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parejasButtonActionPerformed(evt);
            }
        });

        emparejarButton.setText("EMPAREJAR");
        emparejarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emparejarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(modificarButton)
                .addGap(18, 18, 18)
                .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(arbolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(anillaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addComponent(nacimientoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(machoRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hembraRadioButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vueloRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(crianzaRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(parejaActualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(parejasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(emparejarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(anillaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(7, 7, 7))
                            .addComponent(nacimientoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(parejaActualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(parejasButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(machoRadioButton)
                    .addComponent(hembraRadioButton)
                    .addComponent(jLabel8)
                    .addComponent(vueloRadioButton)
                    .addComponent(crianzaRadioButton)
                    .addComponent(emparejarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(arbolButton)
                        .addComponent(salirButton)
                        .addComponent(eliminarButton)))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
        dialog.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        
        if(PalomaController.eliminarPaloma(paloma.getIdPaloma())){
            JOptionPane.showMessageDialog(this, "Paloma con número de anilla " + paloma.getAnilla() + " eliminada.");
        }
        else{
            JOptionPane.showMessageDialog(this, "No se ha encontrado el Nº de anilla.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        
        if(!Utils.checkField(anillaTextField, 30)){
            JOptionPane.showMessageDialog(this, "El campo anilla no puede estar vacío ni tener más de 30 caracteres.");
            return;
        }
        
        String nombre = nombreTextField.getText();
        LocalDate nacimiento = Utils.checkDateChooser(nacimientoDateChooser);
        if(nacimiento == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de nacimiento.");
            return;
        }
        
        String color = colorTextField.getText(); 
        boolean tipo = vueloRadioButton.isSelected() ? true : false;
        
        String sexoStr = "";
        if(buttonGroup1.getSelection() == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un sexo.");
            return;
        }
        if(machoRadioButton.isSelected()){
            sexoStr = "M";
        } 
        else if(hembraRadioButton.isSelected()){
            sexoStr = "H";
        }
        
        char sexo = sexoStr.charAt(0); 
        String observaciones = observacionesTextArea.getText();

        Paloma nuevaPaloma = new Paloma(paloma.getIdPaloma(), nombre, nacimiento, null, sexo, color, tipo, observaciones);
        
        if(PalomaController.modificarPaloma(nuevaPaloma)){
            JOptionPane.showMessageDialog(this,"Paloma con nº de anilla " + paloma.getAnilla() + " guardada correctamente.");
            JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
            dialog.dispose();
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void parejasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parejasButtonActionPerformed
        
        List<Paloma> parejasList = ParejaController.getParejasList(paloma.getIdPaloma());
        
        if(parejasList == null){
            JOptionPane.showMessageDialog(this,"La paloma con anilla"  + paloma.getAnilla() + " no tiene ninguna pareja asignada.");
            return;
        }
        
        ListaPalomasDialog dialog = new ListaPalomasDialog(null, true, paloma.getIdPaloma());
        dialog.setLocationRelativeTo(this); // centra el dialog sobre el frame
        dialog.setVisible(true); // muestra el dialog
    }//GEN-LAST:event_parejasButtonActionPerformed

    private void emparejarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emparejarButtonActionPerformed

        String anillaPareja = JOptionPane.showInputDialog(
            this,
            "INGRESE EL NUMERO DE ANILLA",
            "EMPAREJAR",
            JOptionPane.QUESTION_MESSAGE
        );
        
        // Compruebo si se ha introducido valor en el campo "anillaPareja"
        if (anillaPareja != null && !anillaPareja.trim().isEmpty()) {
            
            // Busco lq paloma en la BD 
            Paloma pareja = PalomaController.buscarPaloma(anillaPareja.toUpperCase());
            
            // Compruebo que recibo un objeto de tipo Paloma y comparo los sexos
            if(pareja != null){
                
                // Compruebo que las palomas no son del mismo sexo
                if(paloma.getSexo() != pareja.getSexo()){

                    String anillaMacho;
                    String anillaHembra;
                    if(paloma.getSexo() == 'M'){ // Si la paloma es macho
                        anillaMacho = paloma.getAnilla().toUpperCase();
                        anillaHembra = anillaPareja.trim().toUpperCase();
                    } else{
                        anillaMacho = anillaPareja.trim().toUpperCase();
                        anillaHembra = paloma.getAnilla().toUpperCase();
                    }
                    
                    // Commpruebo si la pareja ya existe
                    // Commpruebo si la pareja existe
                    if(ParejaController.parejaExists(anillaPareja, anillaPareja)){
                        JOptionPane.showMessageDialog(this, "LA PAREJA YA EXISTE ACTUALMENTE.");
                        return;
                    }
                    // Llamo a método para emparejar la paloma
                    if(ParejaController.crearPareja(anillaMacho, anillaHembra)) {
                            JOptionPane.showMessageDialog(this, "PAREJA CREADA CORRECTAMENTE.");
                    } else {
                        JOptionPane.showMessageDialog(this, "ERROR AL CREAR LA PAREJA.");
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(this, "LAS PALOMAS EMPAREJADAS SON DEL MISMO SEXO.", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "NO SE HA ENCONTRADO LA ANILLA EN LA BD.");
            }       
        }else{
            JOptionPane.showMessageDialog(this, "DEBE INTRODUCIR UNA ANILLA.");
        }
    }//GEN-LAST:event_emparejarButtonActionPerformed

    private static void cargarDatosPaloma(Paloma paloma){
        anillaTextField.setText(paloma.getAnilla().toUpperCase());
        nombreTextField.setText(paloma.getNombre().toUpperCase());
        colorTextField.setText(paloma.getColor().toUpperCase());
        nacimientoDateChooser.setDate(java.sql.Date.valueOf(paloma.getNacimiento()));
        //parejaActualTextField.setText();
        observacionesTextArea.setText(paloma.getObservaciones());
        if(PalomaController.getGenre(paloma)){
            machoRadioButton.setSelected(true);
        } else{
            hembraRadioButton.setSelected(true);
        }
        if(paloma.isTipo()){
            vueloRadioButton.setSelected(true);
            
        } else if(!paloma.isTipo()){
            crianzaRadioButton.setSelected(false);
        }
        
        String anillaPareja = ParejaController.getPareja(paloma.getIdPaloma(), paloma.getSexo());
        
        parejaActualTextField.setText(anillaPareja);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField anillaTextField;
    private javax.swing.JButton arbolButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private static javax.swing.JTextField colorTextField;
    private static javax.swing.JRadioButton crianzaRadioButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton emparejarButton;
    private static javax.swing.JRadioButton hembraRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private static javax.swing.JRadioButton machoRadioButton;
    private javax.swing.JButton modificarButton;
    private static com.toedter.calendar.JDateChooser nacimientoDateChooser;
    private static javax.swing.JTextField nombreTextField;
    private static javax.swing.JTextArea observacionesTextArea;
    private static javax.swing.JTextField parejaActualTextField;
    private javax.swing.JButton parejasButton;
    private javax.swing.JButton salirButton;
    private static javax.swing.JRadioButton vueloRadioButton;
    // End of variables declaration//GEN-END:variables
}
